# Generated by Django 5.1.6 on 2025-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_remove_product_owned_before"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
